language: node_js

node_js:
  - '8.11.2'

script:
  - npm run migration:test
  - npm test

branches:
  only:
    -develop

env:
  global:
    -SECRET=mischiefmanaged

services:
  - postgresql

addons:
  postgresql: '9.5'

before_script:
  -psql -c 'DROP DATABASE IF EXISTS ridemywaytest;' -U postgres
  -psql -c 'CREATE DATABASE ridemywaytest;' -U postgres

cache:
  directories:
    - 'node_modules'

after_success:
  -npm run coverage
  -npm run coveralls